fix: Return proper values, when worker is in remote-content mode
RedHatInsights/yggdrasil pull request #138
Opened 2023-06-26 16:09 UTC by jirihnidek

* When worker works in remote-content mode and address is set to some URL, then the Transmit function should return values according to result of HTTP request POST

2023-06-26 16:25 UTC, jirihnidek commented
BTW: I can imagine that it could be useful to be able to do other types of requests. Not only `POST`:

https://github.com/RedHatInsights/yggdrasil/pull/138/files#diff-4f76a81b1a8e427b6dddee958ea2632e135639e203b2b5a5c1195ccb31ea9a46L269

2023-06-27 17:10 UTC, subpop requested changes

2023-06-27 17:10 UTC, subpop commented on internal/work/dispatcher.go
> +			log.Debugf("URL: '%v' has no scheme", addr)
I feel like this should be an error that we pass back to the worker. If they are
configured as a RemoteContent worker, but are not sending with a value URL, we
shouldn't just log the error. We should respond with the error.

2023-07-11 14:26 UTC, jirihnidek commented on internal/work/dispatcher.go
> -
Fixed with `goimports`.

2023-07-18 16:41 UTC, subpop approved these changes

2023-07-18 16:41 UTC, merged