[WIP] feat: reworked optional data sent in emitted events
RedHatInsights/yggdrasil pull request #140
Opened 2023-07-18 20:22 UTC by DuckBoss

This commit is proposing a change in how optional data is sent in emitted events
and parsed in the yggdrasil dispatcher to simplify the process if additional optional
data needs to be included in emitted worker events in the future.

This work primarily came out of attempts to add a `responseTo` optional field in the emitted event
while avoiding parsing complications in the dispatcher.

2023-08-15 15:42 UTC, subpop requested changes
I like this approach. Since it already breaks API compatibility, we might as well update the struct and EmitEvent method to expect `map[string]string` types instead.

2023-08-15 15:42 UTC, subpop commented on worker/worker.go
>  func (w *Worker) EmitEvent(event ipc.WorkerEventName, messageID string, message string) error {
This method signature might as well change to accept a `data map[string]string` parameter instead of `message string`.

2023-08-15 15:42 UTC, subpop commented on internal/work/dispatcher.go
> +				event.Message = eventMessageData["message"]
Similarly, the `WorkerEvent` struct should change to have a `data map[string]string` field.

2023-09-01 12:51 UTC, subpop commented
Actually, running `golines` across the whole codebase is easy. I'll do that in a PR now.

2023-09-01 13:54 UTC, DuckBoss commented
> I appreciate the usage of `golines` to wrap long lines into multiple shorter ones. However, the effective change of this PR is difficult to discern due to the extraneous line wraps. Could you please either keep all the formatting changes into a separate commit, or run `golines` over the entire codebase and open a separate PR updating all the lines in one commit. I think I'd prefer the deliberate PR approach, as it can both keep the changes in a single commit _and_ solve this formatting change for us once. But if you'd prefer a single commit on one PR, I understand.

Yeah I had conflicting thoughts about this too, but I agree running it once over the entire PR would be a better idea. It may be a good idea to update the "contributing" doc to make golines in future PRs mandatory instead of the current optional suggestion and if possible add a golines check to the linting GH action that's currently in use.

2023-09-06 15:51 UTC, subpop approved these changes
Looks great!

2023-09-06 15:51 UTC, merged