Add a delay before reconnecting to MQTT
RedHatInsights/yggdrasil pull request #161
Opened 2023-09-15 17:29 UTC by subpop

Add a new hidden flag: --mqtt-reconnect-delay. This flag will sleep for the given duration before attempting to reconnect to the MQTT broker. This only works if --mqtt-auto-reconnect is enabled (it is true by default).

I also noticed that the previously added MQTT flags were not set into the DefaultConfig struct, so their values when read from the struct were always the zero value. I fixed this in a separate commit on this same PR.

2023-09-19 14:13 UTC, jirihnidek requested changes
I can confirm that it works, but it is not clear why this new option was added and why `--mqtt-connect-retry-interval` is not enough. I have some comments and proposals how to improve the code.

2023-09-19 14:13 UTC, jirihnidek commented on internal/transport/mqtt.go
> +		log.Debugf("reconnecting to broker: %v", co.Servers)
I would move this `log.Debugf()` at the end of this function.

2023-09-19 15:07 UTC, subpop commented on internal/transport/mqtt.go
> +	opts.SetReconnectingHandler(func(c mqtt.Client, co *mqtt.ClientOptions) {
Yea, the MQTT client package does the backing off itself. We just get a handler that's called before the reconnect attempt happens. I don't think the value is exported by the package at all.

2023-09-19 15:43 UTC, subpop commented on cmd/yggd/main.go
> +		altsrc.NewDurationFlag(&cli.DurationFlag{
Internally, the `DurationFlag` uses [`time.ParseDuration`](https://pkg.go.dev/time#ParseDuration) to parse the value. That function does not make assumptions about default duration unit if the unit is omitted. The error returned by an invalid value for the flag does not make a suggestion about how to specify a valid format. That error comes from the *cli* package though; we can't change it.

These are hidden flags though; their `Usage` won't be visible to a user in the `--help` output. I changed the hidden value to `true` to see what the usage text looks like:

```
--mqtt-reconnect-delay DURATION  Sets the time to wait before attempting to reconnect to DURATION (default: 0s)
```

The default value there hints at using a duration unit, so if we do ever make these visible flags, the usage does suggest to the user how to specify a correct value.

2023-09-20 08:33 UTC, jirihnidek approved these changes
LGTM. Thanks for updates. :+1:

2023-09-20 08:33 UTC, jirihnidek commented on internal/transport/mqtt.go
> +	opts.SetReconnectingHandler(func(c mqtt.Client, co *mqtt.ClientOptions) {
I just noticed that the delay is printed, when `MQTT_DEBUG` is set.

2023-09-20 08:54 UTC, merged