feat: Improve error and debug messaging
RedHatInsights/yggdrasil pull request #238
Opened 2024-06-25 13:12 UTC by jirihnidek

* Improved messaging in various cases (mostly related to D-Bus methods and signals)
* All changes comes from closed PR #157 (running yggdrasil as non-root user)

2024-06-25 14:45 UTC, jirihnidek commented
packit did all checks in 25 minutes ... :-1:

2024-07-10 16:00 UTC, subpop requested changes
Looks great! I just have a couple tiny grammar changes, but otherwise this is good. Very nice improvements.

2024-07-10 16:00 UTC, subpop commented on internal/work/dispatcher.go
> +			"cannot add signal match on the org.freedesktop.DBus.Properties.PropertiesChanged: %v",
Minor grammatical request.
```suggestion
			"cannot add signal match on org.freedesktop.DBus.Properties.PropertiesChanged: %v",
```

2024-07-10 16:00 UTC, subpop commented on internal/work/dispatcher.go
> +			"cannot add signal match on the com.redhat.Yggdrasil1.Worker1.Event: %v",
Minor grammatical request.
```suggestion
			"cannot add signal match on com.redhat.Yggdrasil1.Worker1.Event: %v",
```

2024-07-15 14:13 UTC, subpop approved these changes

2024-07-15 14:13 UTC, merged