feat: HTTP transport add prefix
RedHatInsights/yggdrasil pull request #65
Opened 2022-01-28 14:48 UTC by eloycoto

Currently yggd supports MQTT prefix, in this way adds a prefix to the
MQTT topic. This commit adds the same feature for HTTP, so adds the
prefix to the http endpoint.

Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>

2022-01-28 14:57 UTC, jakub-dzon commented on internal/transport/http.go
> +	path := filepath.Join(yggdrasil.TopicPrefix, channel, t.clientID, direction)
How will that be used by Flotta?

2022-01-28 15:27 UTC, eloycoto commented on internal/transport/http.go
> +	path := filepath.Join(yggdrasil.TopicPrefix, channel, t.clientID, direction)
```
sudo ./yggd  \
  --log-level info \
  --cert-file /tmp/client.pem \
  --key-file /tmp/client.key \
  --protocol http \
  --topic-prefix /api/k4e-management/v1 \
  --ca-root /home/eloy/dev/upstream/eloycoto/mtls_example/certs/rootCA.pem \
  --server localhost:8443
```

2022-01-28 15:29 UTC, jakub-dzon approved these changes
LGTM

2022-01-31 17:54 UTC, subpop requested changes
This looks great. Since we're already breaking the configuration file between 0.2 and 0.3, we should change this flag name to something more generic, so that it applies to both the MQTT and the HTTP transport.

* `--api-prefix`?
* `--path-prefix`?
* `--prefix`?

Any other suggestions?

2022-01-31 20:51 UTC, eloycoto commented
+1 to path-prefix

2022-02-10 14:57 UTC, strider approved these changes
Looks good to me.

2022-02-10 15:31 UTC, merged